### ISSUE TITLE
Add Screenshot to report: ReferenceError: screenshot is not defined

### ISSUE THREAD

**Issue by edgarechm** [wswebcreation/protractor-multiple-cucumber-html-reporter-plugin#16] opened 2018-06-26 18:04 UTC
I spent a while trying to figure out the method to attach screenshots [you shared here](https://www.npmjs.com/package/multiple-cucumber-html-reporter#how-to-attach-screenshots-to-html-report), when using this package. But I was getting the following error:

```
× After # support\hooks.js:16
       ReferenceError: screenshot is not defined
           at C:\workspace\integration\support\hooks.js:19:38
```
But then I realized, there is an error in the snippet:

```
return driver.takeScreenshot()
    .then(function (buffer) {
    	const decodedImage = new Buffer(screenshot.replace(/^data:image\/png;base64,/, ''), 'base64');
        scenario.attach(decodedImage, 'image/png');
  }
```

Your snippet stores return information in a "_buffer_" parameter... but when using the image, you change to use "_screenshot_" instead. Also, why coding then decoding the image?

So I made the some changes to the attach screenshot snippet and got this:

```
var seleniumWebdriver = require('selenium-webdriver');

const {After} = require('cucumber');
	
	After(function(scenario) {
		let self = this;
		return browser.takeScreenshot().then(function (base64png) {
       	              self.attach(new Buffer(base64png, 'base64'), 'image/png');
		});
	});
```
This hooks code, DOES attach screenshot to the report. My only problem is that it **attaches screenshot to ANY outcome**. I tried to use:

```
After(function(scenario) {
	if(scenario.isFailed()){
		let self = this;
		return browser.takeScreenshot().then(function (base64png) {
			self.attach(new Buffer(base64png, 'base64'), 'image/png');
		});
	};
});
```

But got the following error:
```
× After # support\hooks.js:16
       TypeError: scenario.isFailed is not a function
           at World.<anonymous> (C:\workspace\integration\support\hooks.js:17:16)
```

Any idea what could I be missing to make screenshots attach **only when scenario FAILS**?

**Comment by wswebcreation** [comment] 2018-06-29 01:49
Hi @edgarechm 

Tnx for bringing this up. What version of CucumberJS are you using? If you are using version 2 or higher you should use `scenarioResult.status === 'failed'` because `scenario.isFailed()` has been removed when they migrated from version 1 to version 2.

I've updated the readme of `multiple-cucumber-html-reporter` because it could be different for all frameworks.

I'm going to close the issue for now because it's not module related. It's still open for discussion.

**Closed by wswebcreation** 2018-06-29 01:49 UTC

**Comment by edgarechm** [comment] 2018-06-29 15:45
Here are the package versions I'm using:

```
"chromedriver": "2.33.2",
"cucumber": "4.2.1",
"protractor": "5.1.2",
"protractor-cucumber": "0.1.8",
"protractor-cucumber-framework": "5.0.0",
"protractor-multiple-cucumber-html-reporter-plugin": "^1.7.0",
"selenium-server-standalone-jar": "3.4.0",
```

This ---> _**scenarioResult.status === 'failed'**_ , didn't work either. There's no error message, though. But, screenshot is not added to the report.

```
After(function(scenarioResult) {
	if(scenarioResult.status === 'failed'){
		let self = this;
		return browser.takeScreenshot()
	    .then(function (screenshot) {
	    	const decodedImage = new Buffer(screenshot.replace(/^data:image\/png;base64,/, ''), 'base64');
	    	self.attach(decodedImage, 'image/png');
	    });
	};
});
```
So, went back to adding screenshots to any outcome, while I find a solution:
```
After(function(scenarioResult) {
	let self = this;
	return browser.takeScreenshot()
	.then(function (screenshot) {
	    const decodedImage = new Buffer(screenshot.replace(/^data:image\/png;base64,/, ''), 'base64');
	    self.attach(decodedImage, 'image/png');
	});
});
```

**Comment by wswebcreation** [comment] 2018-06-30 13:09
@edgarechm 

Hmm, I think I know where the issue is. Try to do a `console.log('scenarioResult = ', scenarioResult);`
Then you will see there is a `result` object that has a `result` property. There's where you'll find the status value. Then compare it to failed, and you should be done.

Please let me know of it helps.

**Comment by edgarechm** [comment] 2018-07-02 17:01
Actually I had to do this "`console.log('JSON ',JSON.stringify(scenarioResult))`" in order to obtain the property I'm looking for....

So the condition is:

`scenarioResult.result.status === 'failed'`

And yes, I'm enjoying this reporter. Thanks for developing it and for your support.

**My issue has been resolved now**.

**Comment by wswebcreation** [comment] 2018-07-02 17:08
@edgarechm 👍and tnx for the compliments

**Comment by ilijai1** [comment] 2020-05-07 16:26
Hi I am trying to use the same code but apparently  no screenshot is attached at all. If someone can help me check is there a bug in my code or bug in the new package versions:

`//package.json

"cucumber": "^6.0.5",
"cucumber-html-reporter": "^5.2.0",
"protractor": "^5.4.4",
"protractor-cucumber-framework": "^6.2.1",

//hooks.ts

After(function(scenarioResult) {
	if(scenarioResult.result.status === 'failed'){
		let self = this;
		return browser.takeScreenshot()
	    .then(function (screenshot) {
	    	const decodedImage = new Buffer(screenshot.replace(/^data:image\/png;base64,/, ''), 'base64');
	    	self.attach(decodedImage, 'image/png');
	    });
	};
});`
