### ISSUE TITLE
Before hook exception reported as skipped instead of fail 

### ISSUE THREAD

**Issue by ofirmgr** [wswebcreation/protractor-multiple-cucumber-html-reporter-plugin#27] opened 2019-05-27 08:16 UTC
**Environment **
 - protractor-multiple-cucumber-html-reporter: 1.8.0
 - Node.js version: 10.15.0
 - NPM version: 6.8.0
 - Platform name and version: MacOs
 - protractor version: 5.4.1
 - Cucucmber version: 5.1.0
 - protractor-cucumber-framework version: 6.1.1

**Describe the bug**
When error occurs in Before hook the report shows an error on before but in summary it shows as 'skipped'

**To Reproduce**
declare Before hook that return error:

Before(function (scenario, done) {
   done('error');
}

**Expected behavior**
Report should show the Scenario as error

**Actual behavior**
Report show the Scenario as Skipped

**Comment by wswebcreation** [comment] 2019-05-27 10:05
@ofirmgr 

Can you please provide the original create JSON file (so not the merged one) where with the error in the before hook?
Thanks

**Comment by ofirmgr** [comment] 2019-06-01 17:38
here is the original json:
[
  {
    "keyword": "Feature",
    "name": "demo feature",
    "line": 1,
    "id": "demo-feature",
    "tags": [],
    "uri": "e2e/demo.feature",
    "elements": [
      {
        "id": "demo-feature;demo-scenario",
        "keyword": "Scenario",
        "line": 3,
        "name": "demo scenario",
        "tags": [
          {
            "name": "@debug",
            "line": 2
          }
        ],
        "type": "scenario",
        "steps": [
          {
            "keyword": "Before",
            "hidden": true,
            "match": {
              "location": "e2e/steps/common.steps.ts:31"
            },
            "result": {
              "status": "failed",
              "duration": 3000000,
              "error_message": "Error: blabla\n    at World.<anonymous> (e2e/steps/common.steps.ts:32:10)"
            }
          },
          
          {
            "arguments": [],
            "keyword": "Given ",
            "line": 4,
            "name": "TODO",
            "match": {
              "location": "e2e/steps/common.steps.ts:95"
            },
            "result": {
              "status": "skipped"
            }
          },
          {
            "keyword": "After",
            "hidden": true,
            "match": {
              "location": "e2e/steps/common.steps.ts:34"
            },
            "result": {
              "status": "passed",
              "duration": 426000000
            },
            "embeddings": [
              
            ]
          },
          {
            "keyword": "After",
            "hidden": true,
            "match": {
              "location": "node_modules/protractor-cucumber-framework/lib/resultsCapturer.js:26"
            },
            "result": {
              "status": "passed",
              "duration": 1000000
            }
          }
        ]
      }
    ]
  }
]

**Comment by ofirmgr** [comment] 2019-06-01 17:39
[
  {
    "keyword": "Feature",
    "name": "demo feature",
    "line": 1,
    "id": "demo-feature",
    "tags": [],
    "uri": "e2e/demo.feature",
    "elements": [
      {
        "id": "demo-feature;demo-scenario",
        "keyword": "Scenario",
        "line": 3,
        "name": "demo scenario",
        "tags": [
          {
            "name": "@debug",
            "line": 2
          }
        ],
        "type": "scenario",
        "steps": [
          {
            "keyword": "Before",
            "hidden": true,
            "match": {
              "location": "e2e/steps/common.steps.ts:31"
            },
            "result": {
              "status": "failed",
              "duration": 3000000,
              "error_message": "Error: blabla\n    at World.<anonymous> (e2e/steps/common.steps.ts:32:10)"
            }
          },
          
          {
            "arguments": [],
            "keyword": "Given ",
            "line": 4,
            "name": "TODO",
            "match": {
              "location": "e2e/steps/common.steps.ts:95"
            },
            "result": {
              "status": "skipped"
            }
          },
          {
            "keyword": "After",
            "hidden": true,
            "match": {
              "location": "e2e/steps/common.steps.ts:34"
            },
            "result": {
              "status": "passed",
              "duration": 426000000
            },
            "embeddings": [
              
            ]
          },
          {
            "keyword": "After",
            "hidden": true,
            "match": {
              "location": "node_modules/protractor-cucumber-framework/lib/resultsCapturer.js:26"
            },
            "result": {
              "status": "passed",
              "duration": 1000000
            }
          }
        ]
      }
    ]
  }
]

**Comment by ofirmgr** [comment] 2019-06-01 17:41
[
  {
    "keyword": "Feature",
    "name": "demo feature",
    "line": 1,
    "id": "demo-feature",
    "tags": [],
    "uri": "e2e/demo.feature",
    "elements": [
      {
        "id": "demo-feature;demo-scenario",
        "keyword": "Scenario",
        "line": 3,
        "name": "demo scenario",
        "tags": [
          {
            "name": "@debug",
            "line": 2
          }
        ],
        "type": "scenario",
        "steps": [
          {
            "keyword": "Before",
            "hidden": true,
            "match": {
              "location": "e2e/steps/common.steps.ts:31"
            },
            "result": {
              "status": "failed",
              "duration": 3000000,
              "error_message": "Error: blabla\n    at World.<anonymous> (e2e/steps/common.steps.ts:32:10)"
            }
          },
          {
            "arguments": [],
            "keyword": "Given ",
            "line": 4,
            "name": "TODO",
            "match": {
              "location": "e2e/steps/common.steps.ts:95"
            },
            "result": {
              "status": "skipped"
            }
          },
          {
            "keyword": "After",
            "hidden": true,
            "match": {
              "location": "e2e/steps/common.steps.ts:34"
            },
            "result": {
              "status": "passed",
              "duration": 426000000
            },
            "embeddings": [
            ]
          },
          {
            "keyword": "After",
            "hidden": true,
            "match": {
              "location": "node_modules/protractor-cucumber-framework/lib/resultsCapturer.js:26"
            },
            "result": {
              "status": "passed",
              "duration": 1000000
            }
          }
        ]
      }
    ]
  }
]

**Comment by wswebcreation** [comment] 2019-06-02 07:05
Closing this issue because it's an issue with `multiple-cucumber-html-reporter`, I created a new issue, see https://github.com/wswebcreation/multiple-cucumber-html-reporter/issues/87

**Closed by wswebcreation** 2019-06-02 07:05 UTC
Labels: more info needed

**Comment by wswebcreation** [comment] 2019-06-02 08:43
@ofirmgr 

I've been checking this on the `multiple-cucumber-html-reporter` plugin, check the results

![image](https://user-images.githubusercontent.com/11979740/58758910-cca10e00-8522-11e9-8a18-be166f2e81e6.png)


I've also been checking this with this plugin and it also works

![image](https://user-images.githubusercontent.com/11979740/58758916-f0645400-8522-11e9-9606-9b2c6f5039b4.png)


To reproduce this do the following:

1. Clone this module with `git clone https://github.com/wswebcreation/protractor-multiple-cucumber-html-reporter-plugin.git` 
2. Go to the directory `cd protractor-multiple-cucumber-html-reporter-plugin`
3. install the dependencies with `npm i`
4. Go to the file [/test/cucumber/step_definitions/steps.js](https://github.com/wswebcreation/protractor-multiple-cucumber-html-reporter-plugin/blob/master/test/cucumber/step_definitions/steps.js#L3) and at line 3 remove the comment.
5. Run the tests `npm run t`

And check the report, please let me know if this also works for you
